#!/usr/bin/env python3
"""Generate the forwarder thunks and export table for the msi shim.

Reads msi_exports.txt (one "<ordinal>\t<name>" per line, taken from Wine's
msi.spec) and writes:

  exports.h   the export-name table the C code resolves against msi_wine.dll
  stubs32.S   one 5-instruction thunk per export: `jmp *g_real[i]`
  msi.def     the export list with the original ordinals

Only MsiInstallProductA/W get real code (in msi_shim.c); everything else is
a plain jump into Wine's own msi.  Run this file to see exactly what the
shim exports — nothing is hand-written per function.
"""

from __future__ import annotations

from pathlib import Path

HERE = Path(__file__).resolve().parent
INTERCEPTED = ("MsiInstallProductA", "MsiInstallProductW")


def main() -> None:
    rows = [
        line.split("\t")
        for line in (HERE / "msi_exports.txt").read_text().splitlines()
        if line.strip()
    ]
    names = [(int(ordinal), name) for ordinal, name in rows]
    index = {name: i for i, (_, name) in enumerate(names)}
    for name in INTERCEPTED:
        if name not in index:
            raise SystemExit(f"{name} missing from msi_exports.txt")

    header = ["/* generated by gen_forwarders.py — do not edit */", ""]
    header.append(f"#define N_EXPORTS {len(names)}")
    header.append(f"#define IDX_INSTALL_A {index['MsiInstallProductA']}")
    header.append(f"#define IDX_INSTALL_W {index['MsiInstallProductW']}")
    header.append("static const char *const g_name[N_EXPORTS] = {")
    header += [f'    "{name}",' for _, name in names]
    header += ["};", ""]
    (HERE / "exports.h").write_text("\n".join(header))

    asm = ["/* generated by gen_forwarders.py — do not edit */", ".text"]
    for i, (_, name) in enumerate(names):
        if name in INTERCEPTED:
            continue  # implemented in C
        asm += [
            f".globl _{name}",
            f"_{name}:",
            f"    jmp *_g_real+{i * 4}",
            "",
        ]
    (HERE / "stubs32.S").write_text("\n".join(asm))

    definition = ["LIBRARY msi.dll", "EXPORTS"]
    definition += [f"{name} @{ordinal}" for ordinal, name in names]
    (HERE / "msi.def").write_text("\n".join(definition) + "\n")

    print(f"{len(names)} exports: {len(names) - len(INTERCEPTED)} forwarded, "
          f"{len(INTERCEPTED)} intercepted ({', '.join(INTERCEPTED)})")


if __name__ == "__main__":
    main()
