"""native-access:// URLs opened from inside the prefix (Kontakt's Activate
button does ShellExecute("native-access://?action=add-serial")).

NA's installer registers the scheme under the unexpanded name
"${product.uri.scheme}" under Wine, and Wine's HKCR only sees HKLM classes,
so we register it in HKLM ourselves, pointing at a script that runs
`ni launch <url>`.  A script, not the launcher directly: anything started
straight from ShellExecute inherits Wine's dead stdio and hangs.
"""

from __future__ import annotations

from pathlib import Path

from . import config
from .msishim import _ni_command
from .util import info
from .wine import Wine, _reg_default

CLASSES_KEY = rf"Software\Classes\{config.URL_SCHEME}"


def script() -> Path:
    return config.state_dir() / "open-url.sh"


def log() -> Path:
    return config.state_dir() / "open-url.log"


def command(prefix: Path) -> str:
    """The Windows-side command registered for the scheme."""
    del prefix  # the script names the prefix itself
    return rf'C:\windows\system32\start.exe /unix "{script()}" "%1"'


def _script_text(prefix: Path) -> str:
    parts, pythonpath = _ni_command()
    ni = " ".join(f'"{part}"' for part in parts)
    env = f'export PYTHONPATH="{pythonpath}"\n' if pythonpath else ""
    return (
        "#!/bin/sh\n"
        "# Generated by ni-wine; run from inside Wine when a program in the\n"
        "# prefix opens a native-access:// URL (Kontakt's Activate button).\n"
        f"{env}"
        f'exec {ni} --prefix "{prefix}" launch "$@" >>"{log()}" 2>&1 </dev/null\n'
    )


def registered(wine: Wine) -> bool:
    """Cheap check against system.reg (Wine flushes it with a short delay)."""
    return (
        _reg_default(wine.system_reg_text(), rf"{CLASSES_KEY}\shell\open\command")
        == command(wine.prefix)
        and script().is_file()
    )


def ensure(wine: Wine) -> bool:
    """Register the scheme and write its script.  Returns True if changed."""
    changed = False
    text = _script_text(wine.prefix)
    path = script()
    try:
        current = path.read_text()
    except OSError:
        current = None
    if current != text:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
        changed = True
    path.chmod(0o755)

    if _reg_default(wine.system_reg_text(), rf"{CLASSES_KEY}\shell\open\command") != command(wine.prefix):
        hklm = rf"HKLM\{CLASSES_KEY}"
        wine.reg_add(hklm, "", f"URL:{config.URL_SCHEME}")
        wine.reg_add(hklm, "URL Protocol", "")
        wine.reg_add(rf"{hklm}\shell\open\command", "", command(wine.prefix))
        info(f"registered {config.URL_SCHEME}:// URL scheme in the prefix")
        changed = True
    return changed
